apiVersion: v1
kind: Service
metadata:
  name: swarmbrowser-api
  namespace: swarmbrowser
  labels:
    app: swarmbrowser-api
spec:
  type: ClusterIP
  ports:
  - port: 3500
    targetPort: 3500
    protocol: TCP
    name: http
  selector:
    app: swarmbrowser-api
